# Generated by Django 6.0 on 2026-01-02 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Pickels', 'Pickels'), ('Snacks', 'Snacks'), ('Sweets', 'Sweets')], default='BreakFast', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/images')),
                ('tag', models.CharField(default='Veg', help_text='e.g. Veg, BestSeller, Spicy', max_length=20)),
            ],
        ),
    ]
